NAME_FILE = ft_display_file
SRC_FILE = ft_display_file.c
OBJ_FILE = ft_display_file.o

all: $(NAME_FILE)

$(NAEM_FILE): $(OBJ_FILE)
	cc -Wall -Wextra -Werror -o $(NAME_FILE) $(OBJ_FILE)

clean:
	rm -rf $(OBJ_FILE)

fclean: clean
	rm rf $(NAME_FILE)
